### ISSUE TITLE
Binary size

### ISSUE THREAD

**Issue by mxdc** [simonpasquier/prometheus-scaleway-sd#1]
Hello Simon,
When I build from sources with `make build` I get a 60MB binary.
Am I missing something?

Thanks for your work.

**Comment by simonpasquier** [comment]
Yeah this is because `github.com/prometheus/prometheus/discovery` [pulls](https://github.com/prometheus/prometheus/blob/9f4cb06a379c45bb6ec12c241d0492a2f2699887/discovery/manager.go#L28-L38) many 3rd-party dependencies (eg AWS, GCE, Azure, ... clients). The solution would be to decouple the `discovery` package from the actual clients but this work hasn't been started AFAIK.

**Comment by mxdc** [comment]
Hopfully they will change that!
